### PR TITLE
#13 Rebrand

### PR DESCRIPTION
**Pull request by zed13**
1. Replace Siempo launcher icon
2. Replace 'Siempo' with 'Focus launcher' in all texts
3. Remove 'purchase' section in settings
4. Replace Siempo's logo with Focus launcher icon + 'Focus launcher' text.

### CODE REVIEW

**Comment by zed13** [comment]
[launcher3-alpha-debug.zip](https://github.com/focus-launcher/focus-launcher-android/files/6832529/launcher3-alpha-debug.zip)

**Comment by tyler-hitzeman** [comment]
### Some issues I found after testing the APK from that .zip shared above:

Siempo verbiage found on this notification:
- 'Welcome to Siempo! Thank you for your trust'
- Update to 'Welcome to Focus Launcher! ...'

The APK you attached still has the URLs and launch verbage (see screenshots) 

- Update URLs and emails from getsiempo.com to focuslauncher.io destinations
    - Link privacy policy button to link to focuslauncher.io/privacy
    - Link terms of service to focuslauncher.io/terms
    - Update feedback email from feedback@siempo.co to focuslauncher@gmail.com

### Testing tip
I had the original Siempo still installed. I wasn't able to successfully install this Focus Launcher APK until I uninstalled Siempo. I believe this has to do the two currently having the same package name. I documented this in #17


LaunchScreen

**Comment by zed13** [comment]
[launcher3-alpha-debug.zip](https://github.com/focus-launcher/focus-launcher-android/files/6836237/launcher3-alpha-debug.zip)

**Review by tyler-hitzeman — APPROVED** [review]
Tested the APK without seeing the previous issues. Glanced through code and didn't see any obvious issues. Looks good!

**Pull request merged**
