### PR TITLE
Ask permission before enable 'reduce app usage' feature.

### PR DESCRIPTION
**Pull request by zed13**

### CODE REVIEW

**Comment by zed13** [comment]
[launcher3-alpha-debug#30.zip](https://github.com/focus-launcher/focus-launcher-android/files/6911522/launcher3-alpha-debug.30.zip)

**Comment by tyler-hitzeman** [comment]
The permissions & 'reduce app usage' feature worked as expected. But
- The email screen was present 
- The demo screenshot shown before the user was prompted for permissions had the Siempo name and logo. I think this could confuse old Siempo users, so can we replace that image with the screenshot attached (or similar)?
DemoPermissions

**Comment by zed13** [comment]
> The permissions & 'reduce app usage' feature worked as expected. But
> - The email screen was present 
> - The demo screenshot shown before the user was prompted for permissions had the Siempo name and logo. I think this could confuse old Siempo users, so can we replace that image with the screenshot attached (or similar)?
> DemoPermissions
> 

1. Emai request was removed in other PR #.

2  I'll change the screenshot

**Comment by zed13** [comment]
[Uploading launcher3-alpha-debug#30.1.apk.zip…]()

**Comment by tyler-hitzeman** [comment]
> Uploading launcher3-alpha-debug#30.1.apk.zip…

The ZIP isn't actually attached to this comment. Guessing the upload didn't finish.

**Comment by zed13** [comment]
[launcher3-alpha-debug#30.1.apk.zip](https://github.com/focus-launcher/focus-launcher-android/files/6916589/launcher3-alpha-debug.30.1.apk.zip)

**Comment by tyler-hitzeman** [comment]
The updated screenshot looks good, thank you.

The reduce usage feature works, but the flow is bound to confuse some users.

The current behavior:
- User clicks the 'Reduce overuse of flagged apps' toggle to enable it
- User redirected to Usage access screen, clicks Focus Launcher, toggles 'Permit usage access', and clicks back arrow twice
- 'Focus Launcher needs your permission' appears
- User clicks 'ENABLE', then 'GOT IT'
- User enables 'Allow display over other apps', hits back arrow, then goes back to home screen

At this point, the user will assume that the reduce app usage feature is enabled, but it's not -- just the required permissions have been gained. The user would actually need to go back into the settings and click the toggle button again.

I'd suggest:
- redirecting using back to the 'Reduce app usage' screen and enabling the 'Reduce overuse of flagged apps' . That way the user can verify that it's enabled now

----

That said, the feature does work currently. Some users will be bound to figure it out, others won't. That's OK for now.  If you don't have time to update the flow, we can push it off until after getting the app on the play store.

**Comment by tyler-hitzeman** [comment]
Messaged Denis/zed on Discord and agreed to leave as is and tackle the menu flow in another issue.

**Pull request merged**
