### PR TITLE
Google play billing library removed.

### PR DESCRIPTION
**Pull request by bhanup212**
1. ContributeActivity.java removed
2. InAppItemListActivity.java removed
3. SubscriptionUtil.java, SubscriptionItemAdapter.java removed

### CODE REVIEW

**Comment by bhanup212** [comment]
Apk link: https://drive.google.com/file/d/15kgRqup58aIgDQQc9o8l0sd_Ou6rFSsT/view?usp=sharing

**Comment by zed13** [comment]
Consider to remove entry from settings layout file. Everything else is ok.

**Comment by bhanup212** [comment]
@zed13 Alpha setting screen is still being used in app

**Comment by zed13** [comment]
> @zed13 Alpha setting screen is still being used in app
> 

I mean ui item in layout. It's visibility is set to gone.

This one:

```  xml
<LinearLayout android:id="@+id/linInAppProduct" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="15dp" android:orientation="horizontal" android:visibility="gone" tools:ignore="UseCompoundDrawables"> <ImageView android:id="@+id/icon_in_app" android:layout_width="36dp" android:layout_height="36dp" android:layout_gravity="center_vertical" android:layout_marginStart="15dp" android:contentDescription="@null" android:padding="6dp" /> <co.siempo.phone.customviews.RobotoRegularTextView android:id="@+id/txtInAppProduct" android:layout_width="wrap_content" android:layout_height="wrap_content" android:layout_gravity="center_vertical" android:layout_marginStart="15dp" android:fontFamily="sans-serif-medium" android:text="@string/purchase" android:textSize="14sp" /> </LinearLayout>

```

**Comment by bhanup212** [comment]
removed purchase ui from xml

**Review by zed13 — APPROVED** [review]

**Review by tyler-hitzeman — APPROVED** [review]
manual testing of APK passed without issues.

**Comment by bhanup212** [comment]
i am merging this pr then

**Pull request merged**
