### PR TITLE
Removed iap, feedback email, dummy project

### LINKED ISSUE #2: Set up CI
Once we have figured out the local build process, we need to convert this to CI. As part of our org plan we get some free Github actions minutes per month - might be worth looking into.

### PR DESCRIPTION
**Pull request by gdryke**
Just starting on some clean up! I'm not sure on any project direction...but the IAP didn't feel great to me for an open source project, the feedback email was just unsafe (the EverNote creds need to go next, also a question on product direction), and the dummy project seemed useless?

Still seems to build fine though!

### CODE REVIEW

**Review by jlndnn — APPROVED** [review]
Hi Greg, thanks for taking the time to contribute! I agree, there's a lot of stuff we can start getting rid of, the IAB for sure we won't need any time soon. I'm happy to merge this, we can fix the CI up later if it's still being flaky.

**Comment by tyler-hitzeman** [comment]
Thanks for jumping on this @gdryke. Apologies we didn't merge this - I somehow missed it until after merging #14. That one updates the feedback strings, but I believe the other items are still there. Would you be willing to update your branch and retest things?

**Comment by tyler-hitzeman** [comment]
I converted this to a draft, since it's gotten behind the main branch and I haven't heard back from @gdryke. It'd still be good to get these cleanup improvements merged, so anyone who stumbles upon this should feel free to update the branch and re-submit this.

**Comment by tyler-dane** [comment]
This has gone stale and the conflicts are growing, so at this point it'd be easier for someone to create a new PR. Closing this one to keep the repo tidy & relevant.

**Pull request closed without merging**
