### PR TITLE
project gradle updated and maxsdk version set to 30

### PR DESCRIPTION
**Pull request by bhanup212**
1. gradle plugin updated to 4.1.2
2. changed to targetSdkVersion to 30
3. fixed bad notification crash in the above 8.1 version ( required to create a notification channel for foreground services)

### CODE REVIEW

**Comment by zed13** [comment]
It seems that you missed latest changes in master. I've already fixed bug with crushing services.

**Comment by bhanup212** [comment]
I tried pulling changes from master branch but i am not getting as i forked this repo

**Comment by bhanup212** [comment]
Code updated with master branch, any one please review this pr

**Comment by tyler-hitzeman** [comment]
@bhanup212 Can you please make a build and upload it to this issue so I can test things out?

**Comment by bhanup212** [comment]
apk link: https://drive.google.com/file/d/1SnS789M3nqtubJzydfz630cnXot9icCd/view?usp=sharing

**Comment by tyler-hitzeman** [comment]
Thanks! I found this new issue while testing: #33. Everything else worked OK, so I'll merge this and we can tackle that one in another PR

**Pull request merged**
