### PR TITLE
Fix custom background issue

### PR DESCRIPTION
**Pull request by zed13**
- Fix custom background feature for gallery chooser`.
- Fix backgound selection issue for google photos

### CODE REVIEW

**Comment by zed13** [comment]
There are several way to change app's background:
1. Settings / Customize appearance / Custom background toggle
2. Longtap on the screen / Settings icon/ Customize apperance/ Custom
   background toggle.
3. Longtap on the screen / Background icon

**Comment by zed13** [comment]
There are several way to change app's background:
1. Settings / Customize appearance / Custom background toggle
2. Longtap on the screen / Settings icon/ Customize apperance/ Custom
   background toggle.
3. Longtap on the screen / Background icon

**Comment by zed13** [comment]
[launcher3-alpha-debug#15.zip](https://github.com/focus-launcher/focus-launcher-android/files/6880835/launcher3-alpha-debug.15.zip)

**Comment by tyler-hitzeman** [comment]
That was fast! 
Verified this works for both local photos and Google Photos. 
Tested with all 3 triggers listed above (long taps, settings menu)
Other launcher features seem unaffected as well. 

Thanks! 

closes #15

**Pull request merged**
